# Generated by Django 3.2.4 on 2021-06-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
        ('post', '0002_auto_20210626_2049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorypost',
            unique_together={('post_id', 'category_id')},
        ),
    ]
