# Generated by Django 3.2.4 on 2021-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('GENERAL', 'General'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'Python'), ('RUBY', 'Ruby'), ('CPP', 'Cpp'), ('CSHARP', 'Csharp'), ('PHP', 'Php')], default='GENERAL', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
