# Generated by Django 3.2.4 on 2021-06-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('GENERAL', 'General'), ('JAVASCRIPT', 'Javascript'), ('PYTHON', 'Python'), ('RUBY', 'Ruby'), ('CPP', 'Cpp'), ('CSHARP', 'Csharp'), ('PHP', 'Php')], default='GENERAL', max_length=20, unique=True),
        ),
    ]
